#!/usr/bin/env bash
#-------------------------------------------------------------------
# Runs cron jobs of all wpstarter based WordPress sites
# in /etc/nginx/conf.d directory.
#
# I preferred to scan /etc/nginx/conf.d instead of doing a search in
# /var/www or some other place. Virtual host filenames must end with
# 'conf.d'.
#-------------------------------------------------------------------

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin\
:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

if command -v wp >/dev/null 2>&1; then
  WP=$(command -v wp)
else
  echo "Err: WPCLI is not installed."
  exit 1
fi

if [[ -d /etc/nginx/conf.d ]]; then
  mapfile -t VHOSTS < <(/bin/grep -iRls server_name /etc/nginx/conf.d/*.conf)
fi

for host in "${VHOSTS[@]}"; do
  # Parse root directive in vhost config file
  root_line=$(
    /bin/grep -s -E '^[[:space:]]*?root[[:space:]]{1}[a-zA-Z0-9\/\.\-]+;$' "$host"
  )
  root_line=$(echo $root_line) # Trim spaces
  root=$(echo "$root_line" | cut -d" " -f2 | tr -d ';')

  # Make sure this is a wpstarter based WP site
  if [[ -f "$root/../wpstarter.json" ]]; then
    owner=$(stat -c "%U" "$(dirname "$root")")

    # Run cron jobs
    sudo -u "$owner" "$WP" --path="$root/cms" cron event run --due-now
  fi
done
